### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by bkielbasa** [covergates/covergates#23]
Hello!

I'd like to help to build support for bitbucket but I need a bit of help with it :)

I can see you recently added support for [GitLab](https://github.com/covergates/covergates/pull/21/files) what's cool and I'll base my work on it.

**Comment by blueworrybear** [comment]
Hi, @bkielbasa! 
I saw your PR. Thank you for helping! I really appreciate it.
I will read your code this weekend if I have time. Sorry for having kept you waiting.
I am just busy with my job recently.

Anyway, thank you again!

**Comment by bkielbasa** [comment]
@blueworrybear any feedback?

**Comment by bkielbasa** [comment]
@blueworrybear ping!
